### PR TITLE
Migrate existing adapters

### PR DESCRIPTION
**Pull request by rexwangcc**
Corresponding ticket: 
- https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-525

Changes: 
- Move everything under `adapter_pipelines` from [pipeline-tools](https://github.com/HumanCellAtlas/pipeline-tools) here, without changing any contents on the fly.
- Add a few repo level configs, such as the PR template and the security notes.

### CODE REVIEW

**Comment by samanehsan** [comment]
Could we rename `Optimus` to `optimus` for consistency? We'll have to change the path to the files anyways, so I think now is a good time to fix this

**Comment by rexwangcc** [comment]
> Could we rename Optimus to optimus for consistency? We'll have to change the path to the files anyways, so I think now is a good time to fix this

It is an absolutely great idea! Doing it right now!

**Comment by samanehsan** [comment]
Also I've been wanting to rename `adapter_example_static.json` to `static_inputs.json` since they are actually being used as pipeline inputs (not just as an example)!

**Review by charlesdyan — APPROVED** [review]

**Review by samanehsan — APPROVED** [review]

**Comment by rexwangcc** [comment]
> Also I've been wanting to rename adapter_example_static.json to static_inputs.json since they are actually being used as pipeline inputs (not just as an example)!

I will do it in a separate PR so the actual file changes don't hide in massive directory additions.

**Pull request merged**
